### PR TITLE
docs: new banner

### PR DESCRIPTION
**Pull request by tsjazil**

### CODE REVIEW

**Comment by ghostx31** [comment]
Hey thanks for the PR! Just wanted to let you know that going ahead, we're moving forward with `.webp` based screenshots. 
Can you update your screenshots in the `.webp` format and update the PR?

**Comment by tsjazil** [comment]
Ok

**Comment by tsjazil** [comment]
Changed banner to `.webp` format

**Comment by ghostx31** [comment]
Do you mind adding all your flavour screenshots as `.webp` in the PR too? Replace the existing screenshots. 
Thanks again!

**Comment by tsjazil** [comment]
Added SS of diff flavours seperately

**Comment by nekowinston** [comment]
Thanks!

**Comment by tsjazil** [comment]
Welcome :)

**Pull request merged**
